---
-   hosts: localhost
    connection: local
    user: "{{ bash_username }}"
    roles:
        - localhost
        - chrome
        - slack
        - dropbox
        - vagrant
        - git-ubuntu
    tasks:
        -   name: 'TASK: Add color prompt'
            lineinfile:
                path: '/home/{{ bash_username }}/.bashrc'
                regexp: '.force_color_prompt=yes'
                line: 'force_color_prompt=yes'
            run_once: true
        -   name: 'TASK: Fix locales'
            command: '{{ item }}'
            with_items:
                - "sed -i '/^#.* uk_UA.* /s/^#//' /etc/locale.gen"
                - 'locale-gen'
            run_once: true;
#        -   name: 'TASK: set permissions'
#            file:
#                path: '{{ item }}'
#                owner: '{{ bash_username }}'
#                group: '{{ bash_username }}'
#                recurse: true
#            with_items:
    vars:
        bash_username: stsykalovskyi
        git_user_name: '{{ bash_username }}'
        git_user_email: 'stsykalovskyi@singlehop.com'
        vagrant_version: "2.0.2"
        services_repos:
            - { name: ai-ipam, dest: ipam }
            - { name: rbac-beta, dest: rbac }
        projects_repos:
            - { name: perukar.ml, dest: perukar.ml }
            - { name: quizhub.tk, dest: quizhub.tk }
        ssh_files:
            - { name: 'id_rsa', mode: '0400' }
            - { name: 'id_rsa.pub', mode: '0644' }
            - { name: 'config', mode: '0755' }
            - { name: '{{ bash_username }}.pem', mode: '0755' }
