---
-   hosts: localhost
    sudo: yes
    connection: local
    user: "{{ bash_username }}"
    roles:
        - localhost
        - chrome
        - slack
        - dropbox
    tasks:
        -   name once: true;
    vars:
        bash_username: stsykalovskyi
        git_user_name: '{{ bash_username }}'
        git_user_email: 'stsykalovskyi@singlehop.com'
        linux_desktop: kde
        services_repos:
            - { name: ai-ipam, dest: ipam }
        ssh_files:
            - { name: 'id_rsa', mode: '0400' }
            - { name: 'id_rsa.pub', mode: '0644' }
            - { name: 'config', mode: '0755' }
            - { name: '{{ bash_username }}.pem', mode: '0755' }