---
-   hosts: localhost
    connection: local
    user: "{{ bash_username }}"
    roles:
        - localhost
        - chrome
        - slack
        - dropbox
        - vagrant
        - git-ubuntu
    tasks:
        -   name: 'TASK: Add color prompt'
            lineinfile:
                path: '/home/{{ bash_username }}/.bashrc'
                regexp: '.force_color_prompt=yes'
                line: 'force_color_prompt=yes'
        -   name: 'TASK: Fix locales'
            command: '{{ item }}'
            with_items:
                - "sed -i '/^#.* uk_UA.* /s/^#//' /etc/locale.gen"
                - 'locale-gen'
    vars:
        bash_username: stsykalovskyi
        git_user_name: '{{ bash_username }}'
        git_user_email: 'stsykalovskyi@singlehop.com'
        vagrant_version: "2.0.2"
        services_repos:
            - { name: ai-ipam, dest: ipam }
            - { name: rbac-beta, dest: rbac }
        projects_repos:
            - { name: perukar.ml, dest: perukar.ml }
            - { name: quizhub.tk, dest: quizhub.tk }
        ssh_files:
            - { name: 'id_rsa', mode: '0600', owner: '{{ bash_username }}', group: '{{ bash_username }}' }
            - { name: 'id_rsa.pub', mode: '0644', owner: '{{ bash_username }}', group: '{{ bash_username }}' }
            - { name: 'config', mode: '0644', owner: '{{ bash_username }}', group: '{{ bash_username }}' }
            - { name: '{{ bash_username }}.pem', mode: '0600', owner: '{{ bash_username }}', group: '{{ bash_username }}' }
        hosts:
            - { regexp: "192.168.0.100 ", line: "192.168.0.100 rbac.local ipam.local audit.local" }
            - { regexp: "192.168.0.101 ", line: "192.168.0.101 quizhub.tk.local" }
