-   hosts: microservices
    sudo: yes
    user: "{{ bash_username }}"
    roles:
        -   git
        -   php71
        -   composer
        -   nginx
        -   utils

    handlers:
        -   name: Start Nginx
            service: name=nginx state=started
    vars:
        microservices:
            -   name: rbac
                host: rbac.local
            -   name: ipam
                host: ipam.local
        symfony_root_dir: /var/www/services
        bash_username: vagrant
        bash_password: "{{ bash_username }}"
        upload_max_file_size: 2M
        max_input_vars: 1000
        memory_limit: -1
        listen_user: "{{ bash_username }}"
        listen_group: "{{ bash_username }}"
        git_user_email: stsykalovskyi@singlehop.com
        git_user_name: stsykalovskyi
        git_version: 2.16.1