---
-   hosts: microservices
    sudo: yes
    user: "{{ bash_username }}"
    roles:
        - utils
        - pip
        - docker
        - php71-centos
        - git-centos
        - composer
        - openssl
        - nginx-centos
        - microservices
    tasks:
        -   name: 'colorize prompt'
            lineinfile:
                regexp: 'PS1='
                path: '/home/{{ bash_username }}/.bashrc'
                line: PS1='\[\033[01;36m\]\u@\h\[\033[00m\]:\[\033[01;32m\]\w\[\033[00m\] '
        -   name: 'fix locales'
            command: 'localedef -c -f UTF-8 -i uk_UA uk_UA.UTF-8'
    vars:
        microservices:
            -   name: rbac
                host: rbac.stage.shim.singlehop.net.local
            -   name: ipam
                host: ipam.stage.dpc.singlehop.net.local
            -   name: cab
                host: cab.stage.dpc.singlehop.net.local
        openssl_self_signed:
            -   name: rbac.stage.shim.singlehop.net.local
            -   name: ipam.stage.shim.singlehop.net.local
            -   name: cab.stage.shim.singlehop.net.local
        utils:
            - mc
            - nano
            - curl
            - telnet
            - make
        hosts:
            - esrmq01.shim.stage.chi03.singlehop.local
        pip_package: python-pip
        pip_install_packages:
            -   name: httpie
        symfony_root_dir: /var/www/services
        bash_username: vagrant
        bash_password: "{{ bash_username }}"
        upload_max_file_size: 2M
        max_input_vars: 1000
        memory_limit: -1
        listen_user: "{{ bash_username }}"
        listen_group: "{{ bash_username }}"
        git_user_email: stsykalovskyi@singlehop.com
        git_user_name: stsykalovskyi
        git_version: 2.16.2
        composer_github_oauth_token: ebb2353ed432cdd891cde1d2b5fe953d964b39f0
#        ansible_private_key_file: /drives/drive0/vagrant/machines/microservices/.vagrant/machines/default/virtualbox/private_key
