-   hosts: microservices
    sudo: yes
    user: vagrant
    tasks:
        -   name: Install epel
            yum: name=epel-release state=present
            when: ansible_os_family == "RedHat"

        -   name: Install Nginx CentOS
            yum: name=nginx state=present
            when: ansible_os_family == "RedHat"

        -   name: Restart nginx
            service: name=nginx state=restarted enabled=yes

        -   name: Add Symfony config template to the Nginx available sites
            become: true
            template:
                src: templates/symfony.conf
                dest: "/etc/nginx/sites-available/{{ server_name }}.conf"

        -   name: Enable Symfony config template from Nginx available sites
            become: true
            file:
                src: "/etc/nginx/sites-available/{{ server_name }}.conf"
                dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
                state: link

        -   name: Add enabled Nginx site to /etc/hosts
            become: true
            lineinfile:
                dest: /etc/hosts
                regexp: "{{ server_name }}"
                line: "127.0.0.1 {{ server_name }} "

    handlers:
        -   name: Start Nginx
            service: name=nginx state=started
    vars:
        server_name: rbac.local
        symfony_root_dir: /var/www/services
        symfony_web_dir: "{{ symfony_root_dir }}/web"
