---
-   hosts: projects
    sudo: yes
    user: "{{ bash_username }}"
    roles:
#        - git-ubuntu
#        - php71-ubuntu
#        - composer
#        - utils-ubuntu
#        - nodejs
#        - bower
#        - nginx-projects
#        - postgresql
#        - symfony_config
#        - elasticsearch-ubuntu
#        - rabbitmq-ubuntu
        - symfony_config

    vars:
        projects:
            -   name: gamehub
                host: gamehub.com
#            -   name: quizhub
#                host: quizhub.com
        ansible_private_key_file: /drives/drive0/vagrant/machines/projects/.vagrant/machines/default/virtualbox/private_key
        postgres_version: 9.4.11
        bash_username: vagrant
        bash_password: "{{ bash_username }}"
        upload_max_file_size: 2M
        max_input_vars: 1000
        memory_limit: -1
        listen_user: "{{ bash_username }}"
        listen_group: "{{ bash_username }}"
        git_user_email: stsykalovskyi@singlehop.com
        git_user_name: stsykalovskyi
        git_version: 2.16.1
        projects_web_path: /var/www/projects
        postgresql_databases:
            -   name: gamehub
            -   name: quizhub
        rabbitmq_queues:
            - test_q
