---
-   hosts: projects
    sudo: yes
    user: "{{ bash_username }}"
    roles:
        - utils
        - docker
        - git-ubuntu
        - php71-ubuntu
        - composer
        - nodejs
        - bower
        - openssl
        - nginx-ubuntu
        - projects
        - postfix
        -   role: ansible-dkim
            vars:
                domain_name: stsykalovskyi.tk.local
                dkim_domains: '{{ domain_name }}'
                dkim_selector: mail
    tasks:
        -   name: 'TASK: Add color prompt'
            lineinfile:
                path: '/home/{{ bash_username }}/.bashrc'
                regexp: '.force_color_prompt=yes'
                line: 'force_color_prompt=yes'
            run_once: true
        -   name: 'TASK: Fix locales'
            command: '{{ item }}'
            with_items:
                - "sed -i '/^#.* uk_UA.* /s/^#//' /etc/locale.gen"
                - 'locale-gen'
            run_once: true
    vars:
        utils:
            - mc
            - curl
            - unzip
            - default-jdk
            - npm
            - nodejs-legacy
            - ruby
            - zip
        projects:
            -   name: quizhub
                host: quizhub.tk.local
                provider: symfony
            -   name: perukar
                host: perukar.ml.local
                provider: laravel
            -   name: stsykalovskyi
                host: stsykalovskyi.tk.local
                provider: laravel
        ansible_private_key_file: /drives/drive0/vagrant/machines/projects/.vagrant/machines/default/virtualbox/private_key
        bash_username: vagrant
        bash_password: "{{ bash_username }}"
        upload_max_file_size: 2M
        max_input_vars: 1000
        memory_limit: -1
        listen_user: "{{ bash_username }}"
        listen_group: "{{ bash_username }}"
        git_user_email: stsykalovskyi@singlehop.com
        git_user_name: stsykalovskyi
        git_version: 2.16.1
        projects_web_path: /var/www/projects
        composer_github_oauth_token: ebb2353ed432cdd891cde1d2b5fe953d964b39f0
        postgresql_version: 9.5
        postgresql_databases: []
        rabbitmq_queues:
            - test_q
