---
-   hosts: quizhub.tk
    sudo: yes
    user: "{{ bash_username }}"
    roles:
#        - git-ubuntu
#        - php71-ubuntu
#        - composer
#        - utils-ubuntu
#        - nodejs
#        - bower
#        - nginx-ubuntu
#        - postgresql
#        - symfony_config
#        - elasticsearch-ubuntu
#        - rabbitmq-ubuntu
        - symfony-bundles
#    tasks:
#        -   name: 'TASK: Add color prompt'
#            lineinfile:
#                path: '/home/{{ bash_username }}/.bashrc'
#                regexp: '.force_color_prompt=yes'
#                line: 'force_color_prompt=yes'
#            run_once: true
#        -   name: 'TASK: Fix locales'
#            command: '{{ item }}'
#            with_items:
#                - "sed -i '/^#.* uk_UA.* /s/^#//' /etc/locale.gen"
#                - 'locale-gen'
#            run_once: true;
    vars:
        bundles:
#            - default_config
#            - localization
#            - migrations
#            - user
            - lte-admin
#            - oauth
#            - api_doc
#            - oauth-server
        ansible_private_key_file: /drives/drive0/vagrant/machines/projects/.vagrant/machines/default/virtualbox/private_key
        postgres_version: 9.4.11
        bash_username: vagrant
        bash_password: "{{ bash_username }}"
        upload_max_file_size: 2M
        max_input_vars: 1000
        memory_limit: -1
        listen_user: "{{ bash_username }}"
        listen_group: "{{ bash_username }}"
        git_user_email: stsykalovskyi@gmail.com
        git_user_name: stsykalovskyi
        git_version: 2.16.1
        project_name: quizhub
        project_host: quizhub.tk
        projects_web_path: /var/www/projects
        database:
            schema: '{{ project_name }}'
        project_web_path: "{{ projects_web_path }}/{{ project_host }}"
        core_bundle_name: Core
        core_bundle_full_name: "{{ project_name|title }}{{ core_bundle_name }}Bundle"
        namespace: "{{ project_name|title }}\\{{ core_bundle_name }}Bundle"
        composer_autoload_bundles:
            - Admin
            - User
            - Core
        postgresql_databases:
            -   name: quizhub_tk
        rabbitmq_queues:
            - test_q
        parameters_clean:
            - database_host
            - database_driver
            - database_port
            - database_name
            - database_user
            - database_password
            - mailer_transport
            - mailer_user
            - mailer_password
            - mailer_host
            - 'driver: pdo_mysql'
            - "transport: '%mailer_transport%'"
            - "host: '%mailer_host%'"
            - "username: '%mailer_user%'"
            - "password: '%mailer_password%'"
        config_data_set:
            - { name: "password: '%database.password%'", value: "        password: '%database.password%'", after: '    dbal:'}
            - { name: "user: '%database.user%", value: "        user: '%database.user%'", after: '    dbal:'}
            - { name: "dbname: '%database.name%", value: "        dbname: '%database.name%'", after: '    dbal:'}
            - { name: "port: '%database.port%", value: "        port: '%database.port%'", after: '    dbal:'}
            - { name: 'driver: "%database.driver%"' , value: '        driver: "%database.driver%"', after: '    dbal:'}
            - { name: "host: '%database.host%'", value: "        host: '%database.host%'", after: '    dbal:'}
            - { name: "username: '%mailer.user%'" , value: "    username: '%mailer.user%'", after: '^swiftmailer:'}
            - { name: "password: '%mailer.password%'" , value: "    password: '%mailer.password%'", after: '^swiftmailer:'}
            - { name: "transport: '%mailer.transport%'" , value: "    transport: '%mailer.transport%'", after: '^swiftmailer:'}
            - { name: "host: '%mailer.host%'" , value: "    host: '%mailer.host%'", after: '^swiftmailer:'}
            - { name: "project_name: '%project.name%'" , value: "        project_name: '%project.name%'", after: '\t*globals:'}
            - { name: "project_hostname: '%project.hostname%'" , value: "        project_hostname: '%project.hostname%'", after: '\t*globals:'}

        parameters_data_set:
            - { name: database.password, value: '{{ project_name }}_stage' }
            - { name: database.user, value: '{{ project_name }}_stage' }
            - { name: database.driver, value: 'pdo_pgsql' }
            - { name: database.name, value: '{{ project_database }}' }
            - { name: database.port, value: 6432 }
            - { name: database.host, value: 'pg.local' }
            - { name: mailer.transport, value: smtp }
            - { name: mailer.user, value: default }
            - { name: mailer.password, value: default }
            - { name: mailer.host, value: localhost }
            - { name: elasticsearch.host, value: es.local }
            - { name: elasticsearch.port, value: 9200 }
            - { name: project.hostname, value: '{{ project_host }}.local' }
            - { name: project.name, value: '{{ project_name|title }}' }
        gitignore:
            - tests/_output/*
            - .idea
            - web/bundles