---
-   hosts: stlhub.tk
    sudo: yes
    user: "{{ bash_username }}"
    roles:
        - git-ubuntu
        - php71-ubuntu
        - composer
        - utils-ubuntu
        - nodejs
        - bower
        - nginx-ubuntu
        - postgresql
#        - symfony_config
#        - elasticsearch-ubuntu
#        - rabbitmq-ubuntu
    tasks:
        -   name: 'TASK: Add color prompt'
            lineinfile:
                path: '/home/{{ bash_username }}/.bashrc'
                regexp: '.force_color_prompt=yes'
                line: 'force_color_prompt=yes'
            run_once: true
        -   name: 'TASK: Fix locales'
            command: '{{ item }}'
            with_items:
                - "sed -i '/^#.* uk_UA.* /s/^#//' /etc/locale.gen"
                - 'locale-gen'
            run_once: true;
    vars:
        projects:
            -   name: stlhub.tk
                host: stlhub.tk
        ansible_private_key_file: /home/stsykalovskyi/.ssh/id_rsa
        postgres_version: 9.4.11
        bash_username: ubuntu
        bash_password: "{{ bash_username }}"
        upload_max_file_size: 2M
        max_input_vars: 1000
        memory_limit: -1
        listen_user: "{{ bash_username }}"
        listen_group: "{{ bash_username }}"
        git_user_email: stsykalovskyi@gmail.com
        git_user_name: stsykalovskyi
        git_version: 2.16.1
        projects_web_path: /var/www/projects
        postgresql_databases:
            -   name: stlhub_tk
#            -   name: quizhub
        rabbitmq_queues:
            - test_q
